import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[window.dimensions]
columns = 130
lines = 45

[window.padding]
x = 5
y = 5

# [window]
# opacity = 0.97
